/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wenld_jpegcompress_JpegUtils */

#ifndef _Included_com_wenld_jpegcompress_JpegUtils
#define _Included_com_wenld_jpegcompress_JpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wenld_jpegcompress_JpegUtils
 * Method:    compressBitmap
 * Signature: (Ljava/lang/Object;III[BZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wenld_jpegcompress_JpegUtils_compressBitmap
  (JNIEnv *, jclass, jobject, jint, jint, jint, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
